import { GlobalStyle } from 'styles';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'SNAPBIVE',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ko">
			<head>
				<link
					rel="stylesheet"
					as="style"
					crossOrigin=""
					href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/variable/pretendardvariable-dynamic-subset.css"
				/>
			</head>
			<GlobalStyle />
			<body className={inter.className}>{children}</body>
		</html>
	);
}
