import type { Metadata } from 'next';
import 'styles/GlobalStyle.css';

export const metadata: Metadata = {
  title: 'SNAPBIVE',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          as="style"
          crossOrigin=""
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/variable/pretendardvariable-dynamic-subset.css"
        />
        <link
          rel="stylesheet"
          href="https://use.typekit.net/cei0oyt.css"
        ></link>
      </head>
      <body>{children}</body>
    </html>
  );
}
