import { GlobalStyle } from 'styles';
import type { Metadata } from 'next';

export const metadata: Metadata = {
 title: 'SNAPBIVE',
 description: 'Generated by create next app',
};

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang="ko">
   <head>
    <link
     rel="stylesheet"
     as="style"
     crossOrigin=""
     href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/variable/pretendardvariable-dynamic-subset.css"
    />
   </head>
   <GlobalStyle />
   <body>{children}</body>
  </html>
 );
}
